version: "3.9"
services:
  discord-chat-gpt:
    container_name: discord-chat-gpt
    build: .
    volumes:
      - ${PWD}/Data:/app/Data
      - ${PWD}/bot_config.json:/app/bot_config.json
    restart: unless-stopped